# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.0"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJSON = "1.7.3"
kotlinxCoroutines = "1.9.0"
ktor = "3.3.0"
koog = "0.5.2"
telegramBot = "6.3.0"
dotenv = "6.5.1"
slf4j = "2.0.16"
exposed = "0.57.0"
sqliteJdbc = "3.47.1.0"
socketio = "2.1.0"
koin = "4.0.0"
jtokkit = "1.1.0"
mcpKotlinSdk = "0.8.1"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koogAgents = { module = "ai.koog:koog-agents-jvm", version.ref = "koog" }
telegramBot = { module = "io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram", version.ref = "telegramBot" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
exposedCore = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposedDao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposedJdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
socketioClient = { module = "io.socket:socket.io-client", version.ref = "socketio" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinLogger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
mcpKotlinSdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcpKotlinSdk" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
ktorClient = ["ktorClientCore", "ktorClientCio", "ktorClientContentNegotiation", "ktorSerializationKotlinxJson"]
exposed = ["exposedCore", "exposedDao", "exposedJdbc"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }